server:
  port: 7201
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7200/eureka/
    instance:
      leaseRenewalIntervalInSeconds : 1
      leaseExpirationDurationInSeconds: 2
ribbon:
  eureka:
    enable: true
